apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/sergsoares/lab-k0s-in-digital-ocean.git
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated: {}