apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argo-cd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 22.1.0
    helm:
      releaseName: traefik
      valueFiles:
      - traefik-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik