apiVersion: v1
kind: Namespace
metadata:
  name: string-is
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: string-is
  namespace: string-is
spec:
  replicas: 1
  selector:
    matchLabels:
      app: string-is      
  template:
    metadata:
      labels:
        app: string-is
    spec:
      containers:
      - name: gowakandabuy
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
            name: http
        image: daveperrett/string-is:latest
---
apiVersion: v1
kind: Service
metadata:
  name: string-is
  namespace: string-is
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: string-is
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: string-is
  namespace: string-is
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
  - host: string-is.lab-k0s.ourlab.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: string-is
            port:
              number: 3000