updateStrategy:
  type: OnDelete

deployment:
  enabled: true
  kind: DaemonSet

service:
  enabled: true
  type: NodePort

ports:
  websecure:
    hostPort: 443
    expose: true
    exposedPort: 443
    protocol: TCP

certResolvers:
  letsencrypt:
    dnsChallenge:
      provider: cloudflare
      delayBeforeCheck: 30
      resolvers:
        - 1.1.1.1
        - 8.8.8.8
    tlsChallenge: true

env:
- name: CF_API_EMAIL
  valueFrom:
    secretKeyRef:
      name: cloudflare-secrets
      key: CF_API_EMAIL
- name: CF_API_KEY
  valueFrom:
    secretKeyRef:
      name: cloudflare-secrets
      key: CF_API_KEY